version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: poetry run python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - 8000:8000
    env_file:
      - .env
    restart: "on-failure"
    depends_on:
      - postgres-db
    networks:
      - hospital-api

  postgres-db:
    image: imresamu/postgis
    platform: linux/arm64
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASS}
      - POSTGRES_DB=${POSTGRES_DBNAME}
    env_file:
      - .env
    restart: "on-failure"
    networks:
      - hospital-api
    healthcheck:
      test:
        ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DBNAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  hospital-api:
    driver: bridge

volumes:
  postgres_data:
